//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataManager.EFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Purchase()
        {
            this.Category = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public int GoodId { get; set; }
    
        public virtual ICollection<Category> Category { get; set; }
        public virtual Good Good { get; set; }
    }
}
